---
Sessão 30 - Prática em R - Machine Learning
Árvores de Decisão para Classificação
---

```{r}
install.packages('rpart', dependencies = T)
library(rpart)
```

Carrega dados de crédito e separa em treino e teste
```{r}
credito = read.csv("Credit.csv")
credito
amostra = sample(2, 1000, replace = T, prob = c(0.7, 0.3))
creditotreino = credito[amostra == 1, ]
creditoteste = credito[amostra == 2, ]
```

Cria modelo, método para classificação
```{r}
arvore = rpart(class ~., data = creditotreino, method = "class")
print(arvore)
```

Impressão da árvore
```{r}
# Executar com ctrl + shift + enter
plot(arvore)
text(arvore, use.n = T, all = T, cex = .8)
```

Previsão
```{r}
teste = predict(arvore, newdata = creditoteste)
head(teste)
```

Adiciona a coluna teste a creditoteste
```{r}
cred = cbind(creditoteste, teste)
cred
```

Cria coluna com resultado categórico
```{r}
cred['Result'] = ifelse(cred$bad >= 0.5, "bad", "good")
cred
```

Matriz de confusão
```{r}
confusao = table(cred$class, cred$Result)
confusao
taxaacerto = (confusao[1] + confusao[4]) / sum(confusao)
taxaacerto
```

