---
Sessão 12 - Prática em R - Gráficos, Visualizações e Dashboards
Faça Você Mesmo
---

Abrindo os dados
```{r}
dados = read.csv("dados.csv", sep = ";", na.strings = "", stringsAsFactors = TRUE)
dados
head(dados)
```

Olhando o resumo dos dados
```{r}
summary(dados)
summary(dados$PIB)
summary(dados$VALOREMPENHO)
```

Instalando paleta de cores
```{r}
install.packages("RColorBrewer")
library(RColorBrewer)
```

Alguns gráficos
```{r}
# Boxplot
boxplot(dados$VALOREMPENHO, main = "Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"), outline = F)
boxplot(dados$PIB ,main = "Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F)

# Histograma
hist(dados$VALOREMPENHO, main = "Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"))
hist(dados$PIB, main = "Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"))
```

Buscando os maiores empenhos
```{r}
# Executar com ctrl + shif + enter
maior_empenho = head(dados[order(-dados$VALOREMPENHO), ], 10)
barplot(maior_empenho$VALOREMPENHO, col = brewer.pal(n = 10, name = "RdBu"), las = 2, main = "Maiores Empenhos")
legend("topright", legend = maior_empenho$MUNICIPIO, col = brewer.pal(n = 10, name = "RdBu"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```

Buscando os maiores pibs
```{r}
# Executar com ctrl + shif + enter
maior_pib = head(dados[order(-dados$PIB), ], 10)
barplot(maior_pib$PIB, col = brewer.pal(n = 10, name = "Spectral"), las = 2, main = "Maiores PIBS")
legend("topright", legend = maior_pib$MUNICIPIO, col = brewer.pal(n = 10, name = "Spectral"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```

Relação entre PIB e Empenho
```{r}
# Calcula qual % de PIB foi empenhado
dados$PROPORCAO = dados$VALOREMPENHO / dados$PIB 
maior_prop = head(dados[order(-dados$PROPORCAO), ], 8)
barplot(maior_prop$PROPORCAO, col=brewer.pal(n = 8, name = "Set2"), las = 2, main = "Maiores Gastos em Proporção ao PIB")
legend("topright", legend = maior_prop$MUNICIPIO, col = brewer.pal(n = 8, name = "Set2"), lty = 1:2, cex = 0.8, ncol = 2, lwd = 4)
box()
```
