---
Sessão 12 - Prática em R - Gráficos, Visualizações e Dashboards
Gráficos Básicos 2
---

Boxplot
```{r}
boxplot(trees$Volume, main = "Árvores", xlab = "Volume")
boxplot(trees$Volume, main = "Árvores", xlab = "Volume", col = "blue", horizontal = TRUE)
boxplot(trees$Volume, main = "Árvores", xlab = "Volume", col = "blue", outline = FALSE)
```

```{r}
# Notch
boxplot(trees$Height, main = "Árvores", xlab = "Altura", col = "blue", notch = TRUE)
# Dados do gráfico
boxplot.stats(trees$Height)
# Lê apenas uma informação
boxplot.stats(trees$Height)$stats
```

Vários Gráficos
```{r}
boxplot(trees)
```

Agregação
```{r}
InsectSprays
spray = aggregate(. ~ spray, data = InsectSprays, sum)
spray
```

Gráfico de Barras
```{r}
# Executar com o ctrl + shift + enter
barplot(spray$count, col = gray.colors(6), xlab = "Spray", ylab = "Total", names.arg = spray$spray)
box()
```

Gráfico de Setor - Pizza
```{r}
pie(spray$count, labels = spray$spray, main = "Spray", col = c(1:6))
```

Pizza com legenda
```{r}
pie(spray$count, labels = NA, main = "Spray", col = c(1:6))
legend("bottomright", legend = spray$spray, cex = 1, fill = c(1:6))
```

