---
Sessão 12 - Prática em R - Gráficos, Visualizações e Dashboards
Lattice
---

```{r}
library(lattice)
```

Boxplot
```{r}
bwplot(trees$Volume)
bwplot(trees$Volume, main = "Árvores", xlab = "Volume")
```

Histograma
```{r}
# aspect é a proporção, nint é o número de quebras, type: percent, count, density
histogram(trees$Volume, main = "Árvores", xlab = "Volume", aspect = 1, type = "percent", nint = 20)
```

Histograma Condicional
```{r}
# Peso das galinhas de acordo com alimentação
chickwts
# Histograma
histogram(chickwts$weight)
# Agregando os dados
aggregate(chickwts$weight, by = list(chickwts$feed), FUN = sum)
# Histograma condicional
histogram(~weight | feed, data = chickwts)
```

Gráfico de Dispersão Condicional
```{r}
# CO2, seis plantas em dois locais, refrigeradas ou não durante a noite
# CO2, conc: concentração de CO2; Uptake: captação de CO2
CO2
xyplot(CO2$conc ~ CO2$uptake)
# Type é a origem
xyplot(CO2$conc ~ CO2$uptake | CO2$Type)
# Refrigerado ou não
xyplot(CO2$conc ~ CO2$uptake | CO2$Treatment)
```

Câncer de Esôfago
```{r}
# agegp: idade; alcgp: álcool; tobgp: tabaco
esoph
dotplot(esoph$alcgp ~ esoph$ncontrols, data = esoph)
dotplot(esoph$alcgp ~ esoph$ncontrols | esoph$tobgp)
```

Matriz de Dispersão
```{r}
splom(~CO2[4:5] | CO2$Type, CO2)
```

Densidade Condicional
```{r}
densityplot(~CO2$conc | CO2$Treatment, plot.points = FALSE)
densityplot(CO2$conc)
densityplot(~CO2$conc | CO2$Treatment)
```

Gráfico 3D
```{r}
# Spray para repelir abelhas
OrchardSprays
cloud(decrease ~ rowpos * colpos, data = OrchardSprays)
cloud(decrease ~ rowpos * colpos, groups = treatment, data = OrchardSprays)
```

Level Plot
```{r}
# Circunferência, largura e volume de árvores
trees
levelplot(Girth ~ Height * Volume, data = trees)
```

































