---
Sessão 33 - Prática em R - Neural Networks e Deep Learning
Faça Você Mesmo
---

Diagnóstico de Doenças em Soja
1. Crie um modelo de ML (pode usar RNA/DL, entre outras)
2. Busque a melhor performance

Conjunto de dados:
19 classes
35 atributos
683 instâncias


```{r}
#install.packages('randomForest',dependencies=T)
library(randomForest)
```

```{r}
#carrega os dados de exemplo
soja = read.csv('soybean.csv', stringsAsFactors = T)
soja
dim(soja)
#classes
unique(soja$class)
```

```{r}
#gera dois conjuntos de dados aleatórios, para teste e treino
#com 70 e 30% das instâncias, aproximadamente
amostra = sample(2,683,replace=T, prob=c(0.7,0.3))
sojatreino = soja[amostra==1,]
sojateste = soja[amostra==2,]
```

```{r}
#constrói o modelo usando dados de treino
floresta = randomForest(class ~ .,data=sojatreino, ntree=100,proximity=T)
floresta
```

```{r}
#testa o modelo fazendo previsão com dados de teste
previsao = predict(floresta,sojateste)
previsao
```
```{r}
#matriz de confusao
floresta$confusion
#Precisão
mean(floresta$confusion[,'class.error'])
```




